services:
  influxdb:
    image: influxdb:2.7
    container_name: toinc_f1_influxdb
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-adminadminadmin}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-toinc_F1}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-openf1}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION:-30d}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-changeme}
    restart: unless-stopped

volumes:
  influxdb_data:

