#!/usr/bin/env python3
import argparse
import asyncio
import json
import os
import signal
import sys
import time
from pathlib import Path

import websockets


DEFAULT_WS_URL = "wss://livetiming.motorsport.com:8080/782179-full/"
DEFAULT_ORIGIN = "https://www.motorsport.com"
DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36"
)


def load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key and key not in os.environ:
            os.environ[key] = value


def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def summarize_text_message(payload: str, preview_chars: int) -> str:
    try:
        data = json.loads(payload)
    except json.JSONDecodeError:
        text = payload.replace("\n", " ").strip()
        return text[:preview_chars]

    parts = []
    for key in ("message_type", "message_action", "timing_type"):
        value = data.get(key)
        if value:
            parts.append(f"{key}={value}")

    html = (
        data.get("message", {})
        .get("params", {})
        .get("message", "")
    )
    if html:
        parts.append(f"html_len={len(html)}")

    summary = " ".join(parts).strip()
    if summary:
        return summary[:preview_chars]
    compact = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return compact[:preview_chars]


def format_text_message(payload: str, full_message: bool, preview_chars: int) -> str:
    if full_message:
        return payload
    text = payload.replace("\n", " ").strip()
    return text[:preview_chars]


async def read_once(
    ws_url: str,
    origin: str,
    user_agent: str,
    reconnect_interval: int,
    preview_chars: int,
    full_message: bool,
) -> None:
    headers = {
        "User-Agent": user_agent,
        "Pragma": "no-cache",
        "Cache-Control": "no-cache",
        "Accept-Language": "zh,en-US;q=0.9,en;q=0.8,zh-CN;q=0.7",
    }

    started = time.monotonic()
    print(f"[{now_iso()}] connect {ws_url} window={reconnect_interval}s", flush=True)

    async with websockets.connect(
        ws_url,
        origin=origin,
        extra_headers=headers,
        compression="deflate",
        open_timeout=15,
        ping_interval=20,
        ping_timeout=20,
        close_timeout=5,
        max_size=2 * 1024 * 1024,
    ) as websocket:
        print(
            f"[{now_iso()}] connected; Sec-WebSocket-Key is auto-generated by websockets "
            f"and will change on next reconnect",
            flush=True,
        )

        while True:
            remaining = reconnect_interval - (time.monotonic() - started)
            if remaining <= 0:
                print(f"[{now_iso()}] rotate connection after {reconnect_interval}s", flush=True)
                await websocket.close()
                return

            try:
                message = await asyncio.wait_for(websocket.recv(), timeout=min(remaining, 3))
            except asyncio.TimeoutError:
                continue

            if isinstance(message, bytes):
                print(
                    f"[{now_iso()}] binary len={len(message)} head={message[:24].hex()}",
                    flush=True,
                )
                continue

            summary = summarize_text_message(message, preview_chars)
            body = format_text_message(message, full_message, preview_chars)
            print(
                f"[{now_iso()}] text len={len(message)} {summary}",
                flush=True,
            )
            print(body, flush=True)


async def main_async(args: argparse.Namespace) -> int:
    stop_event = asyncio.Event()
    cycles = 0

    def _stop(*_args) -> None:
        stop_event.set()

    if hasattr(signal, "SIGINT"):
        signal.signal(signal.SIGINT, _stop)
    if hasattr(signal, "SIGTERM"):
        signal.signal(signal.SIGTERM, _stop)

    while not stop_event.is_set():
        try:
            await read_once(
                ws_url=args.ws_url,
                origin=args.origin,
                user_agent=args.user_agent,
                reconnect_interval=args.reconnect_interval,
                preview_chars=args.preview_chars,
                full_message=args.full_message,
            )
            cycles += 1
            if args.max_cycles > 0 and cycles >= args.max_cycles:
                break
        except Exception as exc:  # noqa: BLE001
            print(f"[{now_iso()}] error {type(exc).__name__}: {exc}", flush=True)

        if stop_event.is_set():
            break

        try:
            await asyncio.wait_for(stop_event.wait(), timeout=args.backoff_seconds)
        except asyncio.TimeoutError:
            pass

    print(f"[{now_iso()}] stopped", flush=True)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Read Motorsport live timing websocket and rotate the connection every N seconds.",
    )
    parser.add_argument("--ws-url", default=os.getenv("MOTORSPORT_LIVE_WS_URL", DEFAULT_WS_URL))
    parser.add_argument("--origin", default=os.getenv("MOTORSPORT_LIVE_ORIGIN", DEFAULT_ORIGIN))
    parser.add_argument(
        "--user-agent",
        default=os.getenv("MOTORSPORT_LIVE_USER_AGENT", DEFAULT_USER_AGENT),
    )
    parser.add_argument("--reconnect-interval", type=int, default=120)
    parser.add_argument("--backoff-seconds", type=int, default=2)
    parser.add_argument("--preview-chars", type=int, default=220)
    parser.add_argument("--max-cycles", type=int, default=0)
    parser.add_argument("--full-message", action="store_true", default=True)
    parser.add_argument("--no-full-message", action="store_false", dest="full_message")
    return parser


def main() -> int:
    backend_dir = Path(__file__).resolve().parents[1]
    load_dotenv(backend_dir / ".env")
    args = build_parser().parse_args()
    return asyncio.run(main_async(args))


if __name__ == "__main__":
    sys.exit(main())
