FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_API_BASE=http://192.168.31.110:8008
ENV VITE_API_BASE=${VITE_API_BASE}

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html/charts

EXPOSE 80
