server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /charts/;
    }

    location /charts/ {
        try_files $uri $uri/ /charts/index.html;
    }
}
