Page({
  data: {
    apiBase: "",
    liveRows: [
      { position: 1, driver: "George Russell", team: "Mercedes", gap: "", time: "1:15.679", tyre: "S", laps: 8, pitCount: 3, teamColor: "#00D2BE" },
      { position: 2, driver: "Oscar Piastri", team: "McLaren", gap: "+0.214", time: "1:15.893", tyre: "S", laps: 6, pitCount: 3, teamColor: "#FF8000" },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari", gap: "+0.243", time: "1:15.922", tyre: "S", laps: 7, pitCount: 4, teamColor: "#E8002D" },
      { position: 4, driver: "Lando Norris", team: "McLaren", gap: "+0.246", time: "1:15.925", tyre: "S", laps: 6, pitCount: 3, teamColor: "#FF8000" },
      { position: 5, driver: "Lewis Hamilton", team: "Ferrari", gap: "+0.702", time: "1:16.381", tyre: "S", laps: 9, pitCount: 3, teamColor: "#E8002D" },
      { position: 6, driver: "Max Verstappen", team: "Red Bull Racing", gap: "+0.755", time: "1:16.434", tyre: "S", laps: 6, pitCount: 3, teamColor: "#3671C6" },
      { position: 7, driver: "Andrea Kimi Antonelli", team: "Mercedes", gap: "+0.821", time: "1:16.500", tyre: "S", laps: 9, pitCount: 3, teamColor: "#00D2BE" },
      { position: 8, driver: "Isack Hadjar", team: "Red Bull Racing", gap: "+1.005", time: "1:16.684", tyre: "S", laps: 9, pitCount: 4, teamColor: "#3671C6" },
      { position: 9, driver: "Nico Hulkenberg", team: "Audi", gap: "+1.282", time: "1:16.961", tyre: "S", laps: 9, pitCount: 5, teamColor: "#52E252" },
      { position: 10, driver: "Arvid Lindblad", team: "RB F1 Team", gap: "+1.341", time: "1:17.020", tyre: "S", laps: 8, pitCount: 4, teamColor: "#5E8FAA" },
      { position: 11, driver: "Gabriel Bortoleto", team: "Audi", gap: "+1.348", time: "1:17.027", tyre: "S", laps: 7, pitCount: 4, teamColor: "#52E252" },
      { position: 12, driver: "Liam Lawson", team: "RB F1 Team", gap: "+1.645", time: "1:17.324", tyre: "S", laps: 8, pitCount: 5, teamColor: "#5E8FAA" },
    ],
    rows: [
      {
        pos: 1,
        driver: 'A. Antonelli',
        team: 'Mercedes',
        number: 12,
        laps: 28,
        time: "1'12.051",
        gap: '',
        interval: '',
        tyre: 'S',
        teamColor: '#00D2BE',
        carAccent: '#00D2BE',
      },
      {
        pos: 2,
        driver: 'M. Verstappen',
        team: 'Red Bull Racing',
        number: 3,
        laps: 26,
        time: "1'12.094",
        gap: '+0.043',
        interval: '0.043',
        tyre: 'S',
        teamColor: '#3671C6',
        carAccent: '#3671C6',
      },
      {
        pos: 3,
        driver: 'L. Hamilton',
        team: 'Ferrari',
        number: 44,
        laps: 28,
        time: "1'12.279",
        gap: '+0.228',
        interval: '0.185',
        tyre: 'S',
        teamColor: '#E8002D',
        carAccent: '#E8002D',
      },
      {
        pos: 4,
        driver: 'C. Leclerc',
        team: 'Ferrari',
        number: 16,
        laps: 29,
        time: "1'12.351",
        gap: '+0.300',
        interval: '0.072',
        tyre: 'S',
        teamColor: '#E8002D',
        carAccent: '#E8002D',
      },
      {
        pos: 5,
        driver: 'I. Hadjar',
        team: 'Red Bull Racing',
        number: 6,
        laps: 25,
        time: "1'12.434",
        gap: '+0.383',
        interval: '0.083',
        tyre: 'S',
        teamColor: '#3671C6',
        carAccent: '#3671C6',
      },
      {
        pos: 6,
        driver: 'G. Russell',
        team: 'Mercedes',
        number: 63,
        laps: 28,
        time: "1'12.445",
        gap: '+0.394',
        interval: '0.011',
        tyre: 'S',
        teamColor: '#00D2BE',
        carAccent: '#00D2BE',
      },
      {
        pos: 7,
        driver: 'O. Piastri',
        team: 'McLaren',
        number: 81,
        laps: 29,
        time: "1'12.624",
        gap: '+0.573',
        interval: '0.179',
        tyre: 'S',
        teamColor: '#FF8000',
        carAccent: '#FF8000',
      },
      {
        pos: 8,
        driver: 'L. Norris',
        team: 'McLaren',
        number: 1,
        laps: 28,
        time: "1'12.765",
        gap: '+0.714',
        interval: '0.141',
        tyre: 'S',
        teamColor: '#FF8000',
        carAccent: '#FF8000',
      },
      {
        pos: 9,
        driver: 'P. Gasly',
        team: 'Alpine',
        number: 10,
        laps: 32,
        time: "1'13.226",
        gap: '+1.175',
        interval: '0.461',
        tyre: 'S',
        teamColor: '#2293D1',
        carAccent: '#2293D1',
      },
      {
        pos: 10,
        driver: 'L. Lawson',
        team: 'Racing Bulls',
        number: 30,
        laps: 29,
        time: "1'13.412",
        gap: '+1.361',
        interval: '0.186',
        tyre: 'S',
        teamColor: '#5E8FAA',
        carAccent: '#5E8FAA',
      },
    ],
  },
  onLoad() {
    try {
      const app = getApp()
      const apiBase = app && app.globalData && app.globalData.apiBase ? String(app.globalData.apiBase) : ""
      this.setData({ apiBase })
    } catch (e) {}
  },
})
